apiVersion: v1
kind: Service
metadata:
  name: lineten-service
  namespace: lineten
  labels:
    app: lineten-app
spec:
  type: LoadBalancer
  selector:
    app: lineten-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080