azure_subscription_id=""

environment_name="dev"
resource_group_location="germanywestcentral" # one of: australiacentral,australiacentral2,australiaeast,australiasoutheast,brazilsouth,brazilsoutheast,brazilus,canadacentral,canadaeast,centralindia,centralus,centraluseuap,eastasia,eastus,eastus2,eastus2euap,francecentral,francesouth,germanynorth,germanywestcentral,israelcentral,italynorth,japaneast,japanwest,jioindiacentral,jioindiawest,koreacentral,koreasouth,malaysiasouth,mexicocentral,newzealandnorth,northcentralus,northeurope,norwayeast,norwaywest,polandcentral,qatarcentral,southafricanorth,southafricawest,southcentralus,southeastasia,southindia,spaincentral,swedencentral,swedensouth,switzerlandnorth,switzerlandwest,uaecentral,uaenorth,uksouth,ukwest,westcentralus,westeurope,westindia,westus,westus2,westus3,australiaeastfoundational,austriaeast,chilecentral,eastusslv,indonesiacentral,israelnorthwest,malaysiawest,southcentralus2,southeastus,southwestus

aks_dns_prefix="lineten-assignment-aks"
aks_node_count=1
aks_node_type="Standard_DS2_v2"